name: Use GitHub App
on:
  workflow_dispatch:
  
  push:
    paths:
    - .github/workflows/use-github-app.yml

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v4
      with:
        application_id: ${{ vars.GH_APPLICATION_ID }}
        application_private_key: ${{ secrets.GH_APPLICATION_KEY }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.get_workflow_token.outputs.token }}
        repository: hcruz-topcon/demo-app
    - name: log datetime
      run: |
        datetime >> log.txt
        cat log.txt

